// Code generated by gen/main.go. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/grafana/jfr-parser/parser/types/def"
	"github.com/grafana/jfr-parser/util"
)

type BindPackage struct {
	Temp   Package
	Fields []BindFieldPackage
}

type BindFieldPackage struct {
	Field     *def.Field
	SymbolRef *SymbolRef
}

func NewBindPackage(typ *def.Class, typeMap *def.TypeMap) *BindPackage {
	res := new(BindPackage)
	res.Fields = make([]BindFieldPackage, 0, len(typ.Fields))
	for i := 0; i < len(typ.Fields); i++ {
		switch typ.Fields[i].Name {
		case "name":
			if typ.Fields[i].Equals(&def.Field{Name: "name", Type: typeMap.T_SYMBOL, ConstantPool: true, Array: false}) {
				res.Fields = append(res.Fields, BindFieldPackage{Field: &typ.Fields[i], SymbolRef: &res.Temp.Name})
			} else {
				res.Fields = append(res.Fields, BindFieldPackage{Field: &typ.Fields[i]}) // skip changed field
			}
		default:
			res.Fields = append(res.Fields, BindFieldPackage{Field: &typ.Fields[i]}) // skip unknown new field
		}
	}
	return res
}

type PackageRef uint32
type PackageList struct {
	IDMap   map[PackageRef]uint32
	Package []Package
}

type Package struct {
	Name SymbolRef
}

func (this *PackageList) Parse(data []byte, bind *BindPackage, typeMap *def.TypeMap) (pos int, err error) {

	v32_, err := util.ParseVarInt(data, &pos)
	if err != nil {
		return 0, err
	}
	_ = v32_

	n := int(v32_)
	this.IDMap = make(map[PackageRef]uint32, n)
	this.Package = make([]Package, n)
	for i := 0; i < n; i++ {

		v32_, err := util.ParseVarInt(data, &pos)
		if err != nil {
			return 0, err
		}
		_ = v32_

		id := PackageRef(v32_)
		for bindFieldIndex := 0; bindFieldIndex < len(bind.Fields); bindFieldIndex++ {
			bindArraySize := 1
			if bind.Fields[bindFieldIndex].Field.Array {

				v32_, err := util.ParseVarInt(data, &pos)
				if err != nil {
					return 0, err
				}
				_ = v32_

				bindArraySize = int(v32_)
			}
			for bindArrayIndex := 0; bindArrayIndex < bindArraySize; bindArrayIndex++ {
				if bind.Fields[bindFieldIndex].Field.ConstantPool {

					v32_, err := util.ParseVarInt(data, &pos)
					if err != nil {
						return 0, err
					}
					_ = v32_

					switch bind.Fields[bindFieldIndex].Field.Type {
					case typeMap.T_SYMBOL:
						if bind.Fields[bindFieldIndex].SymbolRef != nil {
							*bind.Fields[bindFieldIndex].SymbolRef = SymbolRef(v32_)
						}
					}
				} else {
					bindFieldTypeID := bind.Fields[bindFieldIndex].Field.Type
					switch bindFieldTypeID {
					case typeMap.T_STRING:

						s_, err := util.ParseString(data, &pos)
						if err != nil {
							return 0, err
						}
						_ = s_

						// skipping
					case typeMap.T_INT:

						v32_, err := util.ParseVarInt(data, &pos)
						if err != nil {
							return 0, err
						}
						_ = v32_

						// skipping
					case typeMap.T_LONG:

						v64_, err := util.ParseVarLong(data, &pos)
						if err != nil {
							return 0, err
						}
						_ = v64_

						// skipping
					case typeMap.T_BOOLEAN:

						b_, err := util.ParseByte(data, &pos)
						if err != nil {
							return 0, err
						}
						_ = b_

						// skipping
					case typeMap.T_FLOAT:

						v32_, err := util.ParseVarInt(data, &pos)
						if err != nil {
							return 0, err
						}
						_ = v32_

						// skipping
					default:
						bindFieldType := typeMap.IDMap[bind.Fields[bindFieldIndex].Field.Type]
						if bindFieldType == nil || len(bindFieldType.Fields) == 0 {
							return 0, fmt.Errorf("unknown type %d", bind.Fields[bindFieldIndex].Field.Type)
						}
						bindSkipObjects := 1
						if bind.Fields[bindFieldIndex].Field.Array {

							v32_, err := util.ParseVarInt(data, &pos)
							if err != nil {
								return 0, err
							}
							_ = v32_

							bindSkipObjects = int(v32_)
						}
						for bindSkipObjectIndex := 0; bindSkipObjectIndex < bindSkipObjects; bindSkipObjectIndex++ {
							for bindskipFieldIndex := 0; bindskipFieldIndex < len(bindFieldType.Fields); bindskipFieldIndex++ {
								bindSkipFieldType := bindFieldType.Fields[bindskipFieldIndex].Type
								if bindFieldType.Fields[bindskipFieldIndex].ConstantPool {

									v32_, err := util.ParseVarInt(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = v32_

								} else if bindSkipFieldType == typeMap.T_STRING {

									s_, err := util.ParseString(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = s_

								} else if bindSkipFieldType == typeMap.T_INT {

									v32_, err := util.ParseVarInt(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = v32_

								} else if bindSkipFieldType == typeMap.T_FLOAT {

									v32_, err := util.ParseVarInt(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = v32_

								} else if bindSkipFieldType == typeMap.T_LONG {

									v64_, err := util.ParseVarLong(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = v64_

								} else if bindSkipFieldType == typeMap.T_BOOLEAN {

									b_, err := util.ParseByte(data, &pos)
									if err != nil {
										return 0, err
									}
									_ = b_

								} else {
									return 0, fmt.Errorf("nested objects not implemented. ")
								}
							}
						}
					}
				}
			}
		}
		this.Package[i] = bind.Temp
		this.IDMap[id] = uint32(i)
	}
	return pos, nil
}
